### PR TITLE
manhattan plot not show when NaN in variant_bins(json file)

### PR DESCRIPTION
**Pull request by hailingfang**
I run pheweb with my data, which some p value is 0, and manhattan plot
will not show if it json file contain NaN(jquery .getJSON failed). And
this value is generted by self._arounded(math.inf).

### CODE REVIEW

**Comment by pjvandehaar** [comment]
This Manhattan Plot works fine with a pval=0: https://pheweb.org/UKB-TOPMed/pheno/275.1 .  I wonder what the difference is. What `python --version` are you using?

**Comment by benjaminfang** [comment]
Hi, I using python 3.6.12. and the $.getJSON() failed(in pheno.html template).

**Comment by benjaminfang** [comment]
closed

**Comment by daheise** [comment]
I am also having this issue. What was the solution?

**Comment by hoogla** [comment]
Just cross-referencing the issue https://github.com/statgen/pheweb/issues/230, which was submitted two years after this PR got closed. This shows that this can still be a very relevant issue, and the solution provided here by @hailingfang should be more visible.

**Comment by pjvandehaar** [comment]
@hoogla Sorry, you're right I should have merged PR #188 , but now I can't bc the source repo is deleted.  Would you mind submitting a PR to do the same thing, and I'll merge that?

Also, I'll merge any other PR you submit.  I'd like to add you as editor of this repo but I'm not sure if I can.

**Comment by pjvandehaar** [comment]
@hoogla 320 seems like the wrong maximum for the bins.  Shouldn't it be 324, or log10(5e-324)?  I can't remember how this worked.

**Comment by pjvandehaar** [comment]
@hoogla I just committed https://github.com/statgen/pheweb/commit/3d5f9128b057fb843ebe71d9d11551ed0626a474 .  If that's not right please send a better PR.  If I don't reply to a PR, you can email to my username via gmail.

**Pull request closed without merging**
